### ISSUE TITLE
Infinite Scrolling is not so friendly.

### ISSUE THREAD

**Issue by RobotAmiee** [samvermette/SVPullToRefresh#26]
Every time the table to it's end, it will load data automatically, I think it's not should be. When table view to end, footer shows with label "Pull to load more...", and when people drag up then the indicator with label "loading..." shows, and load data. I think it's more friendly, I have work on for this for several hours and over my head. So I come here for your help, could you add the function? Thanks.

**Comment by samvermette** [comment]
@RobotAmiee how would having a "pull to load more" mechanism be more friendly? The whole point of infinite scrolling is that it's frictionless. It loads new data at the very moment when you want to see more data (when you're at the bottom of the table view). 

That's how Twitter, Google and Facebook do it too. Doesn't it bother you in the App Store app having to tap "Load 25 more" instead of having it automatically load and append that new data?

**Comment by RobotAmiee** [comment]
Sorry, it is just my opinion. And thanks for your advice.

**Comment by samvermette** [comment]
@RobotAmiee sorry if I sounded rude. User interface "friendlyness" isn't really a subjective term. Designers usually agree upon whether a UI element or mechanism is intuitive/friendly. That's why I asked why you thought having a "pull to load more" mechanism would be "more friendly". I was curious to know your reasoning, and in the process exposed mine. I didn't mean to shut you down.

**Comment by RobotAmiee** [comment]
I tried some apps, most use the infinite scrolling mechanism as you said. And I test both mechanism, I must say infinite scrolling is more  convenient. When I propose “pull to load more”, I just want to give our user a choice to load data or not, and a choice to save there mobile data usage. I am self not sure about providing the choice to user is necessary. By the way, you're a nice man.

**Comment by samvermette** [comment]
@RobotAmiee the bandwidth concern is a valid one. Maybe the infinite scrolling can get triggered only when the user lift its finger from the screen? Right now I think it gets triggered as soon as the table footer gets visible. That way panning up the tableview to reveal the footer and then panning back up without lifting your finger wouldn't trigger the load...

**Comment by RobotAmiee** [comment]
That's a enhancement, so when people's finger is on screen and slide up to make the footer invisible, then shouldn't load data. Am I right?

**Comment by samvermette** [comment]
@RobotAmiee that's what I'm describing yes. That being said, I think the bandwidth save is less important than the slight amount of time you gain by having it load the data as soon as you reach the footer view. In other words, fast loading is more important than a tiny bit of wasted bandwidth. I have tested the gesture with the Twitter and Facebook apps and that's also how they do it.
