### ISSUE TITLE
'load more' functionality

### ISSUE THREAD

**Issue by gerardp** [samvermette/SVPullToRefresh#4]
Please, add 'load more' functionality at the bottom of the table.

Thanks !

**Comment by samvermette** [comment]
I will add this eventually. Note that it should be designed in a fashion similar to `addPullToRefreshWithActionHandler:` method. Something like: `addInfiniteScrollingWithActionHandler:`. Feel free to implement it yourself and submit a pull request.

**Comment by jmstone617** [comment]
I am working on integrating this into the SVPullToRefresh class, though I only get an hour here and there. I'll have something soon, and I'd love some feedback. Thanks a lot; this is my first contribution to GitHub, so I am still navigating my way around.

**Comment by jmstone617** [comment]
I have it working now so that the user can drag past the last cell and trigger the load. I created a property in the SVPullToRefresh class that allows you to set either the section or row load limit. The SVPullToRefresh and the DragToLoad can be called with a single method `- (void)addPullToRefreshWithActionHandler:andPerpetualLoadHandler:`. In the Demo project, the only additional work is to tell your tableViewDelegate that the number of rows or sections should be the load limit times the number of loaded portions, which is a readonly property managed by SVPullToRefresh.

This is one implementation style. The other would be to automatically load the next portion of content once you scroll past a certain point in the scrollView/tableView. I can work on that implementation, as well. Perhaps by adding a third addPullToRefresh... method similar to `addPullToRefreshWithActionHandler:automaticallyLoadNewContent:(BOOL)shouldLoadNewContent`

**Comment by jmstone617** [comment]
I've renamed the perpetual load handler to `-addPullToRefreshWithActionHandler:andDragToLoadHandler:` to let you drag past the bottom of the scroll view to load more content. I've also added a "lazy" handler called `- (void)addPullToRefreshWithActionHandler:infiniteScrollActionHandler:` that will automatically fire the infiniteScrollingHandler once 80% of the scrollview's content is scrolled through. In SVPullToRefresh I have added a loadNextPortion method to SVPullToRefresh that will handle reloading your tableView or expanding your scrollView's contentSize automatically. Subsequently, you can leave this method call out (it is shown in the demo), and handle the loading action yourself.

**Comment by samvermette** [comment]
See my latest comment on [pull request #10](https://github.com/samvermette/SVPullToRefresh/pull/10).

Will leave this issue open until someone else (or I) come up with a decent implementation of the "load more" functionality. Sorry if I sound rude, I'm just trying to keep SVPullToRefresh a high-quality component.

**Comment by samvermette** [comment]
I just added support for infinite scrolling. It might require a little more testing but seems to do the job pretty good so far. Will close the issue as the core functionality is there, but feel free to report bugs related to it though.
